### ISSUE TITLE
Doesn't have values upon page refresh in firefox

### ISSUE THREAD

**Issue by amene815** [brandonchupp/windtunnel#1]

**Comment by amene815** [comment]
Whenever I refresh the page in firefox on windows, I also seem to need to restart the server in order to have values show up from the sensors.

**Comment by brandonchupp** [comment]
This issue was related to a new Socket io connection being formed on each refresh. The board can only be initialized once. Thus, a refresh requires a restart of the server. This is fixed in commit 519e6eeea39c41b0e2a0b07a30027b0b7e968ba9.
